name: Generate outputs

on: workflow_dispatch

jobs:
  generate-outputs:
    runs-on: ubuntu-latest
    name: Generate ouputs
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Run
      run: |
        make -C outputs -j $(nproc)
